### ISSUE TITLE
ONNX Vulnerabilities

### ISSUE THREAD

**Issue by AVHopp** [emdgroup/baybe#143]
We currently ignore two ONNX vulnerabilities that appear in all versions <=1.15. ONce version 1.16.0 is released (announced for march 18) we need to check these again.

/remind me to deploy on Mar 18

**Comment by Scienfitz** [comment]
\remind me on March 19th

**Comment by AVHopp** [comment]
This has received a new target release date: https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.16.0

/remind me on March 25th
