### ISSUE TITLE
Question: Does the campaign consider the constraints when recommending the next set of parameters? 

### ISSUE THREAD

**Issue by ritalyu17** [emdgroup/baybe#349]
I tried to optimize a [function](https://huggingface.co/spaces/AccelerationConsortium/crabnet-hyperparameter), this function is wrapped and treated as blackbox as set up [here](https://colab.research.google.com/drive/11TWBZpfZzjIzW1YZXXyG25K6Vy57tENL?usp=sharing) in a colab notebook.
The function have constraints, include: 
- x19 < x20
- x6 + x15 <= 1.0

When I have set up the constraints and passed it to the campaign searchspace, I received errors (from different campaigns) like: 

> AppError: The upstream Gradio app has raised an exception: 1 validation error for BlindedParameterization
>   Value error, Received x19=1.9282829821603463e-14 which should be less than x20=1.5484909905601926e-14 [type=value_error, input_value={'x1': 0.0, 'x2': 0.99999...c3_2', 'fidelity1': 0.5}, input_type=dict]

> AppError: The upstream Gradio app has raised an exception: 1 validation error for BlindedParameterization
>   Value error, Received x19=6.260733986110276e-14 which should be less than x20=0.0 [type=value_error, input_value={'x1': 5.226077351257307e...c3_2', 'fidelity1': 0.5}, input_type=dict]

> AppError: The upstream Gradio app has raised an exception: 1 validation error for BlindedParameterization
>   Value error, Received x6=8.651643240363338e-10 and x15=0.999999999143041 which should sum to less than or equal to 1.0 [type=value_error, input_value={'x1': 0.0, 'x2': 0.99999...c3_2', 'fidelity1': 0.5}, input_type=dict]  

From the BayBE constraints tutorial, the constraint validation is done after all the recommendations are made and it also pass a tolerance argument in the validation. While most of the above errors are due to rounding, is there anyway to workaround it since the wrapped function has a strict constraint? Or if there is a better way to do this? Thanks.

**Comment by AdrianSosic** [comment]
Hi @ritalyu17, I don't have access to your notebook but from what I read in your description, you seem to use a set of *continuous* and place *continuous* linear inequality constraints on top, correct?

When you look at the corresponding [example](https://emdgroup.github.io/baybe/examples/Constraints_Continuous/linear_constraints.html) on our doc page, you'll see that the constraint validation is done using a tolerance, for exactly the reason you described. The issue ultimately stems back to how the constraints are handled by the scipy-solvers, which are internally called to generate the new recommendations and which fulfill the constraints only up to a certain numerical resolution. I guess the error would become smaller when switching to a higher floating point accuracy like `float128` but that is neither supported at the moment nor would it completely solve your problem. So I'm afraid the best you can do at the moment is apply a little post-processing yourself, e.g. to round everything below say 1e-8 to zero. I could imagine that we might provide some automatic post-processing like this in the future, where we project back the found solution onto the constraint polytope ...

Any other thoughts, @Scienfitz @AVHopp?

**Comment by Scienfitz** [comment]
I suggest to simply round tiny numbers to exact 0.0

The error is not raised by baybe but by the app, it appears the app doesnt allow for numerical tolerance in its own validation, which is something I would suggest to change

Additionally, the constraints don't seem right to me `x19 < x20` can never be fulfilled if x20 is 0.0 and `0.0 <= x_i <= 1.0`

**Comment by AVHopp** [comment]
This has been discussed in one of our meetings, hence this can be closed. If anything is unclear, feel free to reopen.
