### ISSUE TITLE
Refactor Tolerance Handling for Numerical Parameters

### ISSUE THREAD

**Issue by Scienfitz** [emdgroup/baybe#375]
Tolerance handling needs to be refactored to distinguish two different situations
- how tolerant is the algo to points that lie completely outside of the allowed parameter range (min/max for discrete parameters). This is important as scaling should be done absed on allowed values, and if values are provided that are substantially outside of that range it could lead to problems. This affects discrete as well as continuous parameters
- how tolerant is the algo towards points that lie close but not exactly on discrete sets of values. This is currently implemented but needs a refactor to be consistent and different to the above point. This only relates to discrete parameters

**Comment by AdrianSosic** [comment]
Closed in favor of #428
