### ISSUE TITLE
Would a GPU make this code run faster?

### ISSUE THREAD

**Issue by brandon-holt** [emdgroup/baybe#408]
Would a GPU make this code run faster for making recommendations, training model, etc.?

**Comment by AdrianSosic** [comment]
Hi @brandon-holt, I'm afraid you misunderstood me 😬 The support is **not yet there**. I actually don't expect that much needs to be adjusted to get it running (ideally, this should only require setting some device configuration in a few places) but it's also not a super high priority at the moment, I have to say. Perhaps @Hrovatin can look into this as her next work item? Can discuss this with the team early next week
