### ISSUE TITLE
Protobuf version conflict

### ISSUE THREAD

**Issue by lauri-codes** [emdgroup/baybe#419]
Hi and thanks for the great software!

It looks like there is a version conflict in the dependency tree, which was caused by an update to the [`opentelemetry-proto` package](https://pypi.org/project/opentelemetry-proto/). During installation, I get this warning:

```
The conflict is caused by:
    baybe 0.11.2 depends on protobuf<4 and <=3.20.3
    opentelemetry-proto 1.28.0 depends on protobuf<6.0 and >=5.0
```

I think this was not caught by your test pipelines, because the latest release (`opentelemetry-proto==1.28`) was done after the latest release of BayBE. I think the solution is to either pin the `opentelemetry-proto` package version to 1.27, or then update to `protobuf>=5.0`

**Comment by Scienfitz** [comment]
Hi @lauri-codes 
thanks, will investigate

Another potentially related thing: I noticed that your CI runs in Python 3.9.

baybe does not support 3.9, can you check whether the error is related to that?

**Comment by lauri-codes** [comment]
Thanks  a lot. I just updated the pipelines to use Python 3.12, but still encounter the problem. Here are the full pipeline logs: https://github.com/FAIRmat-NFDI/nomad-bayesian-optimization/actions/runs/11701205033/job/32586812921

**Comment by Scienfitz** [comment]
hotfix is incoming, eta 1-3 hr

**Comment by sara2512** [comment]
Had the same issue, works for me now. Thank you so much.

**Comment by lauri-codes** [comment]
Works perfectly now, thanks a lot for the quick fix!
