### ISSUE TITLE
Re-writing Campaign User Guide

### ISSUE THREAD

**Issue by AVHopp** [emdgroup/baybe#60]
This issue is created to make everybody (specifically @Scienfitz and @AdrianSosic) aware of me starting to re-write the user guide for campaigns.
The corresponding discussion will be closed, and all comments regarding this issue that I should be aware of before opening the PR can be posted here.

**Comment by Scienfitz** [comment]
Here my proposal for the user guide for campaign content:

- Campaign is central to BayBE, encapsulated all main interaction points for the user, data etc...
- There are three main points of interaction
   - Creation
      - From Searchspace and Objective
         - mention more complexcity possible both in object and searchspace with link, but here only a minimal example
      - Mention optional strategy with link
      - From Config
   - Add Measurements
      - also explains details such as parameter tolerance matching if configured, metadata setting  
   - Get Recommendations
      - also explains batch size and Mantra
      - also explains cached recommendations
   - Mention that addign measurements and getting recommendations is flexible and does not follow a strict order 
   - Mention that other forms of manipulating `Campaign`, even if seemingly suggested by autodoc, are disencouraged
- Campaigns can also be fully serialized, useful for this and that, mention limitation

You see, this structure does not follow a use-case (and hence is not very similar to an example) but rather explains all aspects of a `Campaign`. Its very reasonable to do this with specific extremely condensed examples for each of the sub-topics (similar to what Ive tried for the first version of `Constraints`)

Imo we can try to agree on such a list for all other user guides in the discussion, and once agreed convert them to an Issue thats being worked on.

**Comment by AVHopp** [comment]
Thanks for providing the overview. I think your idea of first proposing a structure via a discussion we all agree on, turning it into an issue (which is probably the point in time where we also decide who should be the main author of the user guide?) is probably the best way to go.
I will once more adjust the current PR to follow this structure.

**Comment by AVHopp** [comment]
This is being closed since there is a PR implementing this issue under review.
