### ISSUE TITLE
Operator in ThresholdCondition gives ValueError

### ISSUE THREAD

**Issue by ustojiljkoff** [emdgroup/baybe#68]
Thanks for sharing this work! BayBE is an amazing tool for BO and I sincerely enjoy going through the code. Amazing work, highly appreciated!

Here's one issue that I found:
When one includes operators such as ">", "<", "<=", ">=", a ValueError is given. This is probably due to the list of valid operators, which is set to be ["=", "==", "!="] in conditions.py file (`_valid_tolerance_operators = ["=", "==", "!="]`). Might be worth taking a look into it (or did I miss something?)

Cheers!

**Comment by Scienfitz** [comment]
Hi @ustojiljkoff ,

Many thanks for your report. Can you post the exact line how you initialized your `ThresholdCondition`?

In lieu, I will assume that you might have followed the user guide, wehre unfortunately at the moment we have a slightly faulty example, indicating the use of the `tolerance` option with a `>` operator. However, as you correctly state this is not possible.

To use operators like  ">", "<", "<=", ">=" simply do not use the `tolerance` keyword, like so:
```python
ThresholdCondition( # will select all values above 150
    threshold = 150, 
    operator = ">",
)
```

We are already putting measures to test user guide code in our CI pipeline so this cannot happen easily again.

**Comment by ustojiljkoff** [comment]
Hi @Scienfitz ,

Thank you for your response. Yes, I followed the user guide to some extent, trying to use BayBE for a project I previously worked on. I was using `DiscreteExcludeConstraint` in the following manner:

```python
DiscreteExcludeConstraint(
    parameters = ["Carbonate", "Concentration"], 
    combiner = "AND", 
    conditions = [ 
        SubSelectionCondition(selection = ["Carbonate 1", "Carbonate 2", "Carbonate 3"]),
        ThresholdCondition(
            threshold = 100, #Concentration in mM
            operator = "<=", 
            #tolerance=10 #will raise an error
        ) 
    ]
)
```

Obviously, this isn't possible (and I can't think of a valid reason why it should be). As you stated, removing `tolerance` worked like a charm in my example. However, I thought it makes sense to raise an issue, as it might give a wrong impression to a user following the guide.

Thanks for looking into it and for the clarification!

**Comment by Scienfitz** [comment]
Ok glad to hear that you've got a working script for your situation.

Thanks again for making us aware, a fix for the user guide is one they way!

Closing this Issue as resolved.
